exasol/virtual-schema-common-document

.github/workflows/deploy_schema_documentation.yml, doc/changes/changelog.md, doc/changes/changes_0.4.0.md, pom.xml, src/main/java/com/exasol/adapter/document/mapping/reader/JsonSchemaMappingReader.java, src/main/java/com/exasol/adapter/document/mapping/reader/JsonSchemaMappingValidator.java, src/main/resources/schemas/edml-1.0.0.json, src/main/resources/schemas/edml/v1.0.0.json, src/test/java/com/exasol/adapter/document/AwsExasolTestInterface.java, src/test/java/com/exasol/adapter/document/ExasolTestDatabaseBuilder.java, src/test/java/com/exasol/adapter/document/mapping/MappingTestFiles.java, src/test/java/com/exasol/adapter/document/mapping/reader/JsonSchemaMappingValidatorTest.java, src/test/resources/basicMapping.json, src/test/resources/dataTypeTestMapping.json, src/test/resources/doubleNestedToTableMapping.json, src/test/resources/multiColumnToTableMapping.json, src/test/resources/openLibraryMapping.json, src/test/resources/singleColumnToTableMapping.json, src/test/resources/toJsonMapping.json, src/test/resources/wholeTableToJsonMapping.json
=> #11 Changed EDML version to three digits

src/main/java/com/exasol/adapter/document/DocumentAdapter.java, src/main/java/com/exasol/adapter/document/UdfCallBuilder.java, src/main/java/com/exasol/adapter/document/UdfEntryPoint.java
=> #24 removed hardcoded UDF schema

doc/changes/changes_2.0.0.md, src/main/java/com/exasol/adapter/document/mapping/ConvertableMappingErrorBehaviour.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToVarcharColumnMapping.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToVarcharColumnValueExtractor.java, src/main/java/com/exasol/adapter/document/mapping/reader/ColumnMappingReader.java, src/main/java/com/exasol/adapter/document/mapping/reader/JsonSchemaMappingValidator.java, src/main/resources/schemas/edml-1.1.0.json, src/test/java/com/exasol/adapter/document/mapping/PropertyToVarcharColumnMappingTest.java, src/test/java/com/exasol/adapter/document/mapping/PropertyToVarcharColumnValueExtractorTest.java, src/test/java/com/exasol/adapter/document/mapping/reader/ColumnMappingReaderTest.java
=> #22: EDML: Made behaviour of toVarchar mapping if not string configurable

.github/workflows/dependency_update.yml, doc/changes/changes_2.0.0.md, pom.xml, rules.xml
=> #32 Automated dependency updates

doc/changes/changes_3.0.0.md, pom.xml, src/main/java/com/exasol/adapter/document/UdfCallBuilder.java, src/main/java/com/exasol/sql/expresion/ValueExpressionToJavaObjectConverter.java, src/test/java/com/exasol/adapter/document/UdfCallBuilderTest.java
Closes #44 
Waits for release of https://github.com/exasol/sql-statement-builder/pull/96
=> #44 Correct data types for empty result table

doc/changes/changes_3.0.0.md, src/main/java/com/exasol/adapter/document/DocumentAdapterProperties.java, src/test/java/com/exasol/adapter/document/DocumentAdapterPropertiesTest.java
=> #47: Allowed `buckets/` prefix for `MAPPING` property

doc/changes/changes_4.0.0.md, pom.xml, src/main/java/com/exasol/adapter/document/DataProcessingPipeline.java, src/main/java/com/exasol/adapter/document/DataProcessingPipelineMonitor.java, src/main/java/com/exasol/adapter/document/PipelineMonitor.java, src/main/java/com/exasol/adapter/document/UdfEntryPoint.java, src/main/java/com/exasol/adapter/document/documentfetcher/DocumentFetcher.java, src/main/java/com/exasol/adapter/document/documentpath/DocumentPathExpression.java, src/main/java/com/exasol/adapter/document/mapping/SchemaMapper.java, src/test/java/com/exasol/adapter/document/DataProcessingPipelineTest.java, src/test/java/com/exasol/adapter/document/mapping/SchemaMapperTest.java
=> #65: Decoupled loading and emitting to improve performance

doc/changes/changes_4.0.0.md, error_code_config.yml, pom.xml, src/main/java/com/exasol/adapter/document/mapping/reader/ColumnMappingReader.java, src/main/java/com/exasol/adapter/document/mapping/reader/JsonSchemaMappingReader.java, src/main/java/com/exasol/adapter/document/mapping/reader/validator/JsonSchemaMappingValidator.java, src/main/java/com/exasol/adapter/document/mapping/reader/validator/messageimprover/NoMappingExceptionMessageImprover.java, src/main/java/com/exasol/adapter/document/mapping/reader/validator/messageimprover/UnknownKeyTypeExceptionMessageImprover.java, src/main/java/com/exasol/adapter/document/mapping/reader/validator/messageimprover/UnknownMappingExceptionMessageImprover.java, src/main/java/com/exasol/adapter/document/mapping/reader/validator/messageimprover/WongSchemaExceptionMessageImprover.java, src/main/java/com/exasol/adapter/document/querypredicate/QueryPredicateToBooleanExpressionConverter.java, src/test/java/com/exasol/adapter/document/mapping/reader/ColumnMappingReaderTest.java, src/test/java/com/exasol/adapter/document/mapping/reader/JsonSchemaMappingReaderIT.java, src/test/java/com/exasol/adapter/document/mapping/reader/JsonSchemaMappingValidatorTest.java
=> refactor/79: Update error-code-crawler

dependencies.md, doc/changes/changelog.md, doc/changes/changes_5.0.0.md, pom.xml, src/main/java/com/exasol/adapter/document/documentnode/DocumentBinaryValue.java, src/main/java/com/exasol/adapter/document/documentnode/DocumentNode.java, src/main/java/com/exasol/adapter/document/documentnode/DocumentNodeVisitor.java, src/main/java/com/exasol/adapter/document/documentnode/holder/BinaryHolderNode.java, src/main/java/com/exasol/adapter/document/iterators/AfterAllCallbackIterator.java, src/main/java/com/exasol/adapter/document/iterators/ChunkBuildingIterator.java, src/main/java/com/exasol/adapter/document/iterators/FlatMapIterator.java, src/main/java/com/exasol/adapter/document/iterators/TransformingIterator.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToDecimalColumnValueExtractor.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToJsonColumnValueExtractor.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToVarcharColumnValueExtractor.java, src/main/java/com/exasol/adapter/document/queryplanning/RemoteTableQueryFactory.java, src/test/java/com/exasol/adapter/document/iterators/AfterAllCallbackIteratorTest.java, src/test/java/com/exasol/adapter/document/iterators/ChunkBuildingIteratorTest.java, src/test/java/com/exasol/adapter/document/iterators/FlatMapIteratorTest.java, src/test/java/com/exasol/adapter/document/iterators/TransformingIteratorTest.java, src/test/java/com/exasol/adapter/document/mapping/PropertyToDecimalColumnValueExtractorTest.java, src/test/java/com/exasol/adapter/document/mapping/PropertyToJsonColumnValueExtractorTest.java, src/test/java/com/exasol/adapter/document/mapping/PropertyToVarcharColumnValueExtractorTest.java, src/test/java/com/exasol/adapter/document/queryplanning/RemoteTableQueryFactoryTest.java
=> feature/82: Added interface for binary data

doc/changes/changelog.md, doc/changes/changes_6.0.0.md, pom.xml, src/main/java/com/exasol/adapter/document/DocumentAdapter.java
=> feature/86: Adapter properties in dialects

doc/changes/changes_6.1.0.md, src/main/java/com/exasol/adapter/document/mapping/AbstractColumnMapping.java, src/main/java/com/exasol/adapter/document/mapping/AbstractPropertyToColumnMapping.java, src/main/java/com/exasol/adapter/document/mapping/IterationIndexColumnMapping.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToColumnMapping.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToDecimalColumnMapping.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToJsonColumnMapping.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToVarcharColumnMapping.java, src/main/java/com/exasol/adapter/document/mapping/SourceReferenceColumnMapping.java, src/test/java/com/exasol/adapter/document/DocumentAdapterIT.java, src/test/java/com/exasol/adapter/document/UdfCallBuilderTest.java, src/test/java/com/exasol/adapter/document/mapping/MockPropertyToColumnMapping.java, src/test/java/com/exasol/adapter/document/mapping/PropertyToColumnMappingBuilderQuickAccess.java, src/test/java/com/exasol/adapter/document/mapping/PropertyToDecimalColumnMappingTest.java, src/test/java/com/exasol/adapter/document/mapping/PropertyToDecimalColumnValueExtractorTest.java, src/test/java/com/exasol/adapter/document/mapping/PropertyToJsonColumnMappingTest.java, src/test/java/com/exasol/adapter/document/mapping/PropertyToJsonColumnValueExtractorTest.java, src/test/java/com/exasol/adapter/document/mapping/PropertyToVarcharColumnMappingTest.java, src/test/java/com/exasol/adapter/document/mapping/PropertyToVarcharColumnValueExtractorTest.java
=> refactor/98: Refactored propertyToXxxReaderClasses to use Lombok

doc/changes/changes_6.1.0.md, src/main/java/com/exasol/adapter/document/edml/AbstractToNumberMapping.java, src/main/java/com/exasol/adapter/document/edml/MappingDefinitionVisitor.java, src/main/java/com/exasol/adapter/document/edml/ToDoubleMapping.java, src/main/java/com/exasol/adapter/document/edml/deserializer/MappingDefinitionDeserializer.java, src/main/java/com/exasol/adapter/document/edml/serializer/EdmlSerializer.java, src/main/java/com/exasol/adapter/document/edml/validator/EdmlSchemaValidator.java, src/main/java/com/exasol/adapter/document/mapping/AbstractPropertyToNumberColumnMapping.java, src/main/java/com/exasol/adapter/document/mapping/AbstractPropertyToNumberColumnValueExtractor.java, src/main/java/com/exasol/adapter/document/mapping/ConvertableMappingErrorBehaviour.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToColumnMappingVisitor.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToColumnValueExtractorFactory.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToDecimalColumnValueExtractor.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToDoubleColumnMapping.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToDoubleColumnValueExtractor.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToVarcharColumnMapping.java, src/main/java/com/exasol/adapter/document/mapping/SourceReferenceColumnMapping.java, src/main/java/com/exasol/adapter/document/mapping/converter/EdmlToStagingTableMappingConverter.java, src/main/resources/schemas/edml-1.3.0.json, src/test/java/com/exasol/adapter/document/DataProcessingPipelineTest.java, src/test/java/com/exasol/adapter/document/DocumentAdapterIT.java, src/test/java/com/exasol/adapter/document/edml/deserializer/EdmlDeserializerTest.java, src/test/java/com/exasol/adapter/document/mapping/MockPropertyToColumnMapping.java, src/test/java/com/exasol/adapter/document/mapping/PropertyToDecimalColumnValueExtractorTest.java, src/test/java/com/exasol/adapter/document/mapping/PropertyToDoubleColumnMappingTest.java, src/test/java/com/exasol/adapter/document/mapping/PropertyToDoubleColumnValueExtractorTest.java
=> feature/57: Added toDoubleMapping

dependencies.md, doc/changes/changes_6.1.0.md, pom.xml, src/test/java/com/exasol/adapter/document/DocumentAdapterIT.java, test-project/mock-project/pom.xml
=> bug/101: Fix integration test setup

doc/changes/changes_6.1.0.md, src/main/java/com/exasol/adapter/document/edml/MappingDefinitionVisitor.java, src/main/java/com/exasol/adapter/document/edml/ToBoolMapping.java, src/main/java/com/exasol/adapter/document/edml/ToDoubleMapping.java, src/main/java/com/exasol/adapter/document/edml/deserializer/MappingDefinitionDeserializer.java, src/main/java/com/exasol/adapter/document/edml/serializer/EdmlSerializer.java, src/main/java/com/exasol/adapter/document/mapping/AbstractPropertyToNumberColumnValueExtractor.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToBoolColumnMapping.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToBoolColumnValueExtractor.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToColumnMappingVisitor.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToColumnValueExtractorFactory.java, src/main/java/com/exasol/adapter/document/mapping/converter/EdmlToStagingTableMappingConverter.java, src/main/resources/schemas/edml-1.3.0.json, src/test/java/com/exasol/adapter/document/DocumentAdapterIT.java, src/test/java/com/exasol/adapter/document/mapping/PropertyToBoolColumnMappingTest.java, src/test/java/com/exasol/adapter/document/mapping/PropertyToBoolColumnValueExtractorTest.java
=> feature/104: Added `toBoolMapping` mapping type

doc/changes/changes_6.1.0.md, src/main/java/com/exasol/adapter/document/documentnode/DocumentDateValue.java, src/main/java/com/exasol/adapter/document/documentnode/DocumentNodeVisitor.java, src/main/java/com/exasol/adapter/document/documentnode/DocumentTimestampValue.java, src/main/java/com/exasol/adapter/document/documentnode/holder/ArrayHolderNode.java, src/main/java/com/exasol/adapter/document/documentnode/holder/BigDecimalHolderNode.java, src/main/java/com/exasol/adapter/document/documentnode/holder/BinaryHolderNode.java, src/main/java/com/exasol/adapter/document/documentnode/holder/BooleanHolderNode.java, src/main/java/com/exasol/adapter/document/documentnode/holder/DateHolderNode.java, src/main/java/com/exasol/adapter/document/documentnode/holder/DoubleHolderNode.java, src/main/java/com/exasol/adapter/document/documentnode/holder/NullHolderNode.java, src/main/java/com/exasol/adapter/document/documentnode/holder/ObjectHolderNode.java, src/main/java/com/exasol/adapter/document/documentnode/holder/StringHolderNode.java, src/main/java/com/exasol/adapter/document/documentnode/holder/TimestampHolderNode.java, src/main/java/com/exasol/adapter/document/documentnode/objectwrapper/ObjectWrapperDocumentNodeFactory.java, src/main/java/com/exasol/adapter/document/mapping/AbstractPropertyToNumberColumnValueExtractor.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToBoolColumnMapping.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToBoolColumnValueExtractor.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToJsonColumnValueExtractor.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToVarcharColumnValueExtractor.java, src/test/java/com/exasol/adapter/document/documentnode/objectwrapper/ObjectWrapperDocumentNodeFactoryTest.java, src/test/java/com/exasol/adapter/document/mapping/PropertyToBoolColumnValueExtractorTest.java, src/test/java/com/exasol/adapter/document/mapping/PropertyToDecimalColumnValueExtractorTest.java, src/test/java/com/exasol/adapter/document/mapping/PropertyToDoubleColumnValueExtractorTest.java, src/test/java/com/exasol/adapter/document/mapping/PropertyToJsonColumnValueExtractorTest.java, src/test/java/com/exasol/adapter/document/mapping/PropertyToVarcharColumnValueExtractorTest.java
=> feature/106: Added support for date, time and timestamp input values

doc/changes/changes_6.1.0.md, pom.xml, src/main/java/com/exasol/adapter/document/UdfCallBuilder.java, src/main/java/com/exasol/adapter/document/UdfEntryPoint.java, src/main/java/com/exasol/adapter/document/edml/MappingDefinitionVisitor.java, src/main/java/com/exasol/adapter/document/edml/ToDateMapping.java, src/main/java/com/exasol/adapter/document/edml/ToTimestampMapping.java, src/main/java/com/exasol/adapter/document/edml/deserializer/MappingDefinitionDeserializer.java, src/main/java/com/exasol/adapter/document/edml/serializer/EdmlSerializer.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToColumnMappingVisitor.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToColumnValueExtractorFactory.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToDateColumnMapping.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToDateColumnValueExtractor.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToTimestampColumnMapping.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToTimestampColumnValueExtractor.java, src/main/java/com/exasol/adapter/document/mapping/converter/EdmlToStagingTableMappingConverter.java, src/main/java/com/exasol/sql/expresion/ValueExpressionToJavaObjectConverter.java, src/main/resources/schemas/edml-1.3.0.json, src/test/java/com/exasol/adapter/document/DocumentAdapterIT.java, src/test/java/com/exasol/adapter/document/mapping/PropertyToDateColumnMappingTest.java, src/test/java/com/exasol/adapter/document/mapping/PropertyToDateColumnValueExtractorTest.java, src/test/java/com/exasol/adapter/document/mapping/PropertyToTimestampColumnMappingTest.java, src/test/java/com/exasol/adapter/document/mapping/PropertyToTimestampColumnValueExtractorTest.java, test-project/mock-project/src/main/java/com/exasol/adapter/document/mock/FixedDataAdapter.java
=> feature/58: Added toDate and toTimestamp mapping

doc/changes/changes_6.1.0.md, doc/user_guide/edml_user_guide.md, src/main/java/com/exasol/adapter/document/mapping/AbstractPropertyToNumberColumnValueExtractor.java, src/test/java/com/exasol/adapter/document/mapping/PropertyToDecimalColumnValueExtractorTest.java
=> doc/103: Documented conversions

doc/changes/changes_6.1.0.md, src/main/java/com/exasol/adapter/document/mapping/AbstractPropertyToNumberColumnValueExtractor.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToBoolColumnValueExtractor.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToDateColumnValueExtractor.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToTimestampColumnValueExtractor.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToVarcharColumnValueExtractor.java, src/test/java/com/exasol/adapter/document/mapping/PropertyToVarcharColumnValueExtractorTest.java
=> refactor/112: Refactored PropertyToVarcharColumnValueExtractor

doc/changes/changes_6.1.0.md, doc/user_guide/edml_user_guide.md, src/test/java/com/exasol/adapter/document/DocumentAdapterIT.java
=> feature/96: Add integration test for inline mapping definitions

dependencies.md, doc/changes/changelog.md, doc/changes/changes_6.1.1.md, pom.xml, src/main/java/com/exasol/adapter/document/mapping/ColumnMappingDefinitionKeyTypeReader.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToJsonColumnValueExtractor.java, src/main/java/com/exasol/adapter/document/properties/SchemaMappingPropertyReader.java, src/test/java/com/exasol/adapter/document/mapping/MappingTestFiles.java, test-project/mock-project/pom.xml
=> refactor/117: Replaced javax.json by jakarta.json

.github/workflows/broken_links_checker.yml, .github/workflows/ci-build-next-java.yml, doc/changes/changelog.md, doc/changes/changes_7.0.1.md, pom.xml, src/main/java/com/exasol/adapter/document/mapping/PropertyToColumnMapping.java, test-project/mock-project/pom.xml
=> Dependency Updates

doc/changes/changelog.md, doc/changes/changes_8.1.0.md, pom.xml, src/main/java/com/exasol/adapter/document/connection/ConnectionPropertiesReader.java, src/test/java/com/exasol/adapter/document/connection/ConnectionPropertiesReaderTest.java, test-project/mock-project/pom.xml
=> feature/125: Support JSON formatted connection-properties

dependencies.md, doc/changes/changes_9.0.0.md, pom.xml, src/main/java/com/exasol/adapter/document/iterators/CloseInjectIterator.java, src/test/java/com/exasol/adapter/document/iterators/CloseInjectIteratorTest.java
=> refactor/130: Added CloseInjectIterator

doc/changes/changes_9.0.0.md, src/main/java/com/exasol/adapter/document/UdfCallBuilder.java, src/test/java/com/exasol/adapter/document/UdfCallBuilderTest.java
=> refactor/50: Improved Push down SQL building

.github/workflows/broken_links_checker.yml, .github/workflows/ci-build-next-java.yml, .github/workflows/ci-build.yml, .github/workflows/dependencies_check.yml, .github/workflows/release_droid_prepare_original_checksum.yml, .github/workflows/release_droid_print_quick_checksum.yml, .github/workflows/release_droid_release_on_maven_central.yml, .github/workflows/release_droid_upload_github_release_assets.yml, dependencies.md, doc/changes/changelog.md, doc/changes/changes_9.0.1.md, error_code_config.yml, pk_generated_parent.pom, pom.xml, release_config.yml, src/main/java/com/exasol/adapter/document/iterators/CloseInjectIterator.java, test-project/mock-project/pom.xml
=> bug/141: Made CloseInjectIterator public

doc/changes/changelog.md, doc/changes/changes_9.1.1.md, pk_generated_parent.pom, pom.xml
=> update edml dependency to fix serialisation issue

doc/user_guide/edml_user_guide.md
=> added notes on CSV support

.gitattributes, .github/workflows/release_droid_upload_github_release_assets.yml, .gitignore, .project-keeper.yml, .vscode/settings.json, dependencies.md, doc/changes/changelog.md, doc/changes/changes_9.1.2.md, pk_generated_parent.pom, pom.xml, release_config.yml
=> Updated dependencies

.gitignore, .project-keeper.yml, .settings/org.eclipse.m2e.core.prefs, README.md, dependencies.md, doc/changes/changelog.md, doc/changes/changes_9.4.0.md, doc/user_guide/edml_user_guide.md, pk_generated_parent.pom, pom.xml, src/main/java/com/exasol/adapter/document/UdfCountCalculator.java, src/main/java/com/exasol/adapter/document/querypredicate/QueryPredicateToBooleanExpressionConverter.java, src/test/java/com/exasol/adapter/document/DocumentAdapterIT.java, src/test/java/com/exasol/adapter/document/querypredicate/QueryPredicateToBooleanExpressionConverterTest.java, test-project/mock-project/pom.xml
=> #159 Improve error message

doc/changes/changes_9.4.0.md, src/main/java/com/exasol/adapter/document/mapping/auto/InferredMappingDefinition.java, src/main/java/com/exasol/adapter/document/mapping/auto/SchemaFetcher.java, src/main/java/com/exasol/adapter/document/mapping/auto/SchemaInferencer.java, src/test/java/com/exasol/adapter/document/mapping/auto/SchemaInferencerTest.java, src/test/java/com/exasol/adapter/document/mapping/reader/JsonSchemaMappingReaderIT.java
=> #161: Allow SchemaFetcher to detect additional configuration and description

doc/changes/changelog.md, doc/changes/changes_9.4.1.md, doc/user_guide/edml_user_guide.md, pk_generated_parent.pom, pom.xml
=> #160: Document CSV auto-inference

dependencies.md, doc/changes/changes_9.4.1.md, pom.xml
=> #165: Updated dependencies

dependencies.md, doc/changes/changelog.md, doc/changes/changes_9.4.3.md, doc/user_guide/edml_user_guide.md, error_code_config.yml, pk_generated_parent.pom, pom.xml, src/main/java/com/exasol/adapter/document/mapping/reader/JsonSchemaMappingReader.java, src/test/java/com/exasol/adapter/document/mapping/reader/JsonSample.java, src/test/java/com/exasol/adapter/document/mapping/reader/JsonSchemaMappingReaderIT.java, test-project/mock-project/pom.xml
=> #171: Validate duplicate destination table names

.github/workflows/broken_links_checker.yml, .github/workflows/ci-build-next-java.yml, .github/workflows/ci-build.yml, .github/workflows/dependencies_update.yml, .project-keeper.yml, .vscode/settings.json, dependencies.md, doc/changes/changelog.md, doc/changes/changes_11.0.0.md, doc/user_guide/edml_user_guide.md, pk_generated_parent.pom, pom.xml, src/main/java/com/exasol/adapter/document/DocumentAdapterDialect.java, src/main/java/com/exasol/adapter/document/mapping/PropertyToTimestampColumnMapping.java, src/main/java/com/exasol/adapter/document/mapping/auto/ColumnNameConverter.java, src/main/java/com/exasol/adapter/document/mapping/auto/SchemaFetcher.java, src/main/java/com/exasol/adapter/document/mapping/auto/SchemaInferencer.java, src/main/java/com/exasol/adapter/document/mapping/converter/EdmlToStagingTableMappingConverter.java, src/test/java/com/exasol/adapter/document/DocumentAdapterIT.java, src/test/java/com/exasol/adapter/document/mapping/PropertyToTimestampColumnMappingTest.java, src/test/java/com/exasol/adapter/document/mapping/auto/ColumnNameConverterTest.java, src/test/java/com/exasol/adapter/document/mapping/auto/SchemaInferencerTest.java, src/test/java/com/exasol/adapter/document/mapping/converter/EdmlToStagingTableMappingConverterTest.java, src/test/java/com/exasol/adapter/document/mapping/reader/JsonSchemaMappingReaderIT.java, test-project/mock-project/pom.xml, test-project/mock-project/src/main/java/com/exasol/adapter/document/mock/FixedDataAdapterDialect.java
=> #189: Configure column name converter for auto schema inference

.github/workflows/ci-build.yml, .github/workflows/dependencies_update.yml, .github/workflows/release.yml, dependencies.md, doc/changes/changelog.md, doc/changes/changes_11.0.4.md, pk_generated_parent.pom, pom.xml, src/main/java/com/exasol/adapter/document/mapping/TableMapping.java, src/main/java/com/exasol/adapter/document/queryplanning/RemoteTableQuery.java, src/test/java/com/exasol/adapter/document/mapping/TableMappingTest.java, src/test/java/com/exasol/adapter/document/queryplanning/RemoteTableQueryTest.java
=> Added more logging around the paths that lead to the creation of the query plan.

.github/workflows/dependencies_check.yml, doc/changes/changelog.md, doc/changes/changes_11.0.6.md, pk_generated_parent.pom, pom.xml
=> Fixes CVE-2025-48924
